### ISSUE TITLE
Suggestion: Ability to transfer pet ownership

### ISSUE THREAD

**Issue by RogueRaiden** [G3rste/petai#17]
A few players on my server have been wishing to gift each other pets

**Comment by G3rste** [comment]
I have gotten this request before. I am unsure of how the system should work. I thought of the following concepts:

1. You "abandon" your pet and he gets free for anyone to tame
2. You can set the owner of your pet to another playername
3. You can pick up your pet as an item and whoever spawns it back is the new owner

I tend to the first system because i think it seems to be the most realistic having to gain trust of your new pet.

**Comment by RogueRaiden** [comment]
I think the first system would be great, actually. Then players could also "release" the pet from ownership in general.

...wonder when someone will start a pokemon mod based on this one haha

**Comment by G3rste** [comment]
Do you want to have a look at it pre release?
[petai_v1.3.5.zip](https://github.com/G3rste/petai/files/8064063/petai_v1.3.5.zip)

**Comment by RogueRaiden** [comment]
Some quick server testing and its looking good!
